[[mounts]]
  source = "/home/sheepink/works/contents/sheepink"
  target = "content"
[[mounts]]
  source = "/home/sheepink/works/media/sheepink"
  target = "static"
[[mounts]]
  source = "static"
  target = "static"