[tools]
node = "lts"
"ubi:gohugoio/hugo[matching=extended_withdeploy]" = "0.149.0"
[tasks.sync_r2]
description = "R2にメディア同期"
run = """
rclone sync "/home/sheepink/works/media/sheepink" "sync-sheepink-r2:sheepink-media" --include="*/" --include="*.webp" --progress --stats=30s
"""
[tasks.deploy_wrangler]
description = "Workersをデプロイ"
dir = "/home/sheepink/works/projects/sheepink/production"
run = "npx wrangler deploy"
[tasks.release]
description = "メディア同期とWorkersデプロイ"
depends = ["sync_r2", "deploy_wrangler"]