name = "sheepink-hugo-worker"
compatibility_date = "2025-08-26"
main = "index.js"
[[routes]]
pattern = "sheep.ink"
custom_domain = true
[build]
command = "./build.sh"
[assets]
binding = "ASSETS"
directory = "./public"
not_found_handling = "404-page"
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "sheepink-media"