name = "sheepink-hugo-worker"
compatibility_date = "2025-08-26"
[build]
command = "./build.sh"
[assets]
directory = "./public"
not_found_handling = "404-page"
[vars]
HUGO_ENV = "production"
HUGO_ENVIRONMENT = "production"
GO_VERSION = "1.24.3"
[env.production.vars]
HUGO_ENV = "production"
HUGO_ENVIRONMENT = "production"
GO_VERSION = "1.24.3"
